databases:
  - name: Warudkarbmohan
    databaseName: Warudkarbmohan
    user: mohan
    password: QNByaSUMRGzQeUSsdqqLUAHdI2TJWe4K
    url: postgres://mohan:QNByaSUMRGzQeUSsdqqLUAHdI2TJWe4K@dpg-cli8jreg1b2c73ajtcr0-a.singapore-postgres.render.com/mohan_db
    ipAllowList:
    - source: 0.0.0.0/0
      description: everywhere
      
 services:
 - type: pserv
   name: pgbouncer
   runtime: docker
   plan: free
   repo: https://github.com/mohanwarudkar123/Squadcast-Data-Analysis-and-Manipulation
   envVars:
   - key: DATABASE_URL
     fromDatabase:
       name: Warudkarbmohan
       property: connectionString
   - key: POOL_MODE
     value: transaction
   - key: SERVER_RESET_QUERY
     value: DISCARD ALL
   - key: MAX_CLIENT_CONN
     value: 500
   - key: DEFAULT_POOL_SIZE
     value: 50
